---
title: "Practice Time!"
output: 
  html_document:
    number_sections: true
---

# Welcome to R Markdown

---

This is your first practice file. 

* You can open this file in RStudio and "Knit" it to produce an html file.
* We will use R markdown (Rmd) files like this for the most part of this course. 
* This is a very flexible format that can be used to make reports, dashboards, presentations, and so on. 

## Text

In the text part, R markdown lets you do essential formatting like levels of headings, **bold**, *italics*, bulleted lists, numbered lists, super^script^ and sub~script~, mathematical equations (e.g. $e^{i\pi} = -1$, $Y = \alpha + \beta X$), hyperlinks etc. You can also insert images and tables.

### Exercise

Can you convert the bulleted list above into a numbered list? ([hint](https://www.google.com/search?q=r+markdown+numbered+list))

## Code

Here is an example of how you can mix R code into this document. date() is a small piece of R code that prints the current date and time. Every time you knit this Rmd, you will notice that the code runs again and prints the current time of your computer (Try it!). 

R code in an Rmd usually goes into a code "chunk" like the one below.

```{r}

date()

```

It is also possible to insert R code inline. E.g., the current time is: `r date()` and the time zone is `r Sys.timezone()`.

Does this help you imagine the possibility of creating a document that has dynamic elements updated by code? 

---

*Once you are familiar with the R markdown format, don't forget to use the [R Markdown cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf) as a quick reference. For an extensive coverage of R Markdown, see [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/).*

---

**Happy learning!**

