---
title: "Spatial Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(sf)
library(ggplot2)
library(dplyr)
```

Column {.sidebar}
-----------------------------------------------------------------------

### Introduction

Here we have Indian UAs and districts with their 2011 populations and sex ratios.

Column {.tabset}
-----------------------------------------------------------------------

### Urban Agglomerations

```{r,include=FALSE}
ua_points <- read.csv("data/spatial_data/ua_geocode.csv") #Reading it as csv directly
ua_points <- st_as_sf(ua_points, coords = c("Longitude","Latitude")) #parsing to lat long info

data <- read.csv("data/ua_populations.csv")
geo_data <- merge(ua_points, data, by = "ua_no")

st_crs(geo_data) <- st_crs("EPSG:4326")

india <- st_read("data/spatial_data/india-soi.geojson")

geo_data_2011_sex_ratio <- geo_data %>%
  filter(year == "2011") %>%
  mutate(sex_ratio = 1000*pop_female/pop_male)


ua_plot <- ggplot() + 
  ggtitle("Urban Agglomerations of India by Population and Sex Ratio, 2011") + 
  theme(
    axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_blank()
  ) + 
  geom_sf(data = india, fill = NA) + 
  geom_sf(data = geo_data_2011_sex_ratio, aes(size = population, fill = sex_ratio), shape = 21, color = "grey60") + 
    scale_size_continuous(name = "Population", range = c(0.5,8),
                          limits = c(100000,20000000),
                          breaks = c(100000,500000,1000000,5000000,10000000),
                          labels = c("100,000","500,000","1,000,000","5,000,000","10,000,000")) +
    scale_fill_gradient2(name = "Sex ratio", 
                      low = "red",
                      mid = "white",
                      high = "green",
                      midpoint = 1000)
```

```{r}
ua_plot
```

### District populations

```{r,include=FALSE}
india_pca <- read.csv("data/india_pca.csv")
districts <- india_pca %>%
  filter(Level == "DISTRICT" & TRU == "Total")
districts_geo <- st_read("data/spatial_data/India-Districts-2011Census.shp")

districts_geo_data <- merge(districts_geo, districts, by.x = "censuscode", by.y = "District")


district_pop <- ggplot() + 
  ggtitle("Urban Agglomerations of India by Population and Sex Ratio, 2011") + 
  theme(
    axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_blank()
  ) + 
  geom_sf(data = india, fill = "grey40") + 
  geom_sf(data =  districts_geo_data, aes(fill = TOT_P)) +
  scale_fill_gradient(name = "Population of Indian districts, 2011", 
                      low = "white",
                      high = "slateblue3",
                      limits = c(0,6000000), ## We use limits to ensure that outliers don't dominate the color for the rest of the values
                      oob = scales::squish, ## We squish out of bounds ("oob") values to the limits
                      breaks = c(1500000,3000000,4500000,6000000),
                      labels = c("1,500,000","3,000,000","4,500,000","6,000,000"))
```

```{r}
district_pop
```

### District sex ratio

```{r,include=FALSE}
districts_geo_data_sex_ratio <- districts_geo_data %>%
  mutate(sex_ratio = 1000*TOT_F/TOT_M)

district_sex_ratio <- ggplot() + 
  ggtitle("Urban Agglomerations of India by Population and Sex Ratio, 2011") + 
  theme(
    axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_blank()
  ) + 
  geom_sf(data = india, fill = "grey40") + 
  geom_sf(data =  districts_geo_data_sex_ratio, aes(fill = sex_ratio)) +
  scale_fill_gradient2(name = "Sex ratio of Indian districts, 2011", 
                      low = "red",
                      mid = "white",
                      high = "green",
                      limits = c(850,1100),
                      oob = scales::squish,
                      midpoint = 1000)
```

```{r}
district_sex_ratio
```